import Button from "./Button";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

useGLTF.preload("/prev_button.glb");

export default function Buttons() {

  // Additional unclick handler for play button
  // const playUnclickHandler = ({ setPlaying, playing } : UnclickType ) => {
  //   setPlaying(!playing);
  //   console.log("setting play option");
  // };

  // Additional unclick handler for sound button
  // const soundUnclickHandler = ({ setLol, soundOn } : UnclickType) => {
  //   // setLol(!soundOn);
  //   console.log("setting sound option");
  // };

  return (
    <>
      <Button
        id="soundOnOffButton"
        modelPath={"/models/buttons/soundon_button.glb"}
        modelPathAlternative={"/models/buttons/soundoff_button.glb"}
        position={[2, -1, 4]}
        rotation={[0.5, 0.5, -0.25]}
      />
      <Button
        id="playPauseButton"
        modelPath={"/models/buttons/play_button.glb"}
        modelPathAlternative={"/models/buttons/pause_button.glb"}
        position={[0, -1, 4]}
        rotation={[0.5, 0.5, -0.25]}
      />

      <Button
        id="nextButton"
        modelPath={"/models/buttons/next_button.glb"}
        position={[1, -1, 4]}
        rotation={[0.5, 0.5, -0.25]}
      />
      <Button
        id="prevButton"
        modelPath={"/models/buttons/prev_button.glb"}
        position={[-1, -1, 4]}
        rotation={[0.5, 0.5, -0.25]}
      />
      <Button
        id="homeButton"
        modelPath={"/models/buttons/home_button.glb"}
        position={[-1.85, -0.65, 4.5]}
        rotation={[Math.PI * 0.12, Math.PI * 0.16, -Math.PI * 0.08]}
        spring={{
          scaleNormal: 0.8, //Override defaults
          scalePressed: 0.7,
          scaleHovering: 0.9
          // Using default values for config
        }}
      />
    </>
  );
}
