import { config } from "@react-spring/three";
import Button from "./Button";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

useGLTF.preload("/prev_button.glb");

export default function Buttons({ playing, setPlaying, soundOn, setLol }) {
  const scaleNormal = 0.03;
  const scalePressed = 0.025;
  const hoveringScale = 0.032;
  const springConfig = config.bouncy;

  // Additional unclick handler for play button
  const playUnclickHandler = ({ setPlaying, playing }) => {
    setPlaying(!playing);
    console.log("setting play option");
  };

  // Additional unclick handler for sound button
  const soundUnclickHandler = ({ setLol, soundOn }) => {
    // setLol(!soundOn);
    console.log("setting sound option");
  };

  return (
    <>
      <Button
        id="soundOnOffButton"
        scaleNormal={scaleNormal}
        scalePressed={scalePressed}
        hoveringScale={hoveringScale}
        springConfig={springConfig}
        switchButton={true}
        modelPathOne={"/models/buttons/soundon_button.glb"}
        modelPathTwo={"/models/buttons/soundoff_button.glb"}
        position={[2, -1, 4]}
        rotation={[0.5, 0.5, -0.25]}
        additionalUnclickHandler={soundUnclickHandler}
        additionalUnclickHandlerConfigs={(setLol, soundOn)}
      />
      <Button
        id="playPauseButton"
        scaleNormal={scaleNormal}
        scalePressed={scalePressed}
        hoveringScale={hoveringScale}
        springConfig={springConfig}
        switchButton={true}
        modelPathOne={"/models/buttons/play_button.glb"}
        modelPathTwo={"/models/buttons/pause_button.glb"}
        position={[0, -1, 4]}
        rotation={[0.5, 0.5, -0.25]}
        additionalUnclickHandler={playUnclickHandler}
        additionalUnclickHandlerConfigs={{ setPlaying, playing }}
      />

      <Button
        id="nextButton"
        scaleNormal={scaleNormal}
        scalePressed={scalePressed}
        hoveringScale={hoveringScale}
        springConfig={springConfig}
        switchButton={true}
        modelPathOne={"/models/buttons/next_button.glb"}
        modelPathTwo={"/models/buttons/next_button.glb"}
        position={[1, -1, 4]}
        rotation={[0.5, 0.5, -0.25]}
        additionalUnclickHandler={() => {}}
        additionalUnclickHandlerConfigs={{ setPlaying, playing }}
      />
      <Button
        id="prevButton"
        scaleNormal={scaleNormal}
        scalePressed={scalePressed}
        hoveringScale={hoveringScale}
        springConfig={springConfig}
        switchButton={true}
        modelPathOne={"/models/buttons/prev_button.glb"}
        modelPathTwo={"/models/buttons/prev_button.glb"}
        position={[-1, -1, 4]}
        rotation={[0.5, 0.5, -0.25]}
        additionalUnclickHandler={() => {}}
        additionalUnclickHandlerConfigs={{ setPlaying, playing }}
      />
      <Button
        id="homeButton"
        scaleNormal={0.8}
        scalePressed={0.7}
        hoveringScale={0.9}
        springConfig={springConfig}
        switchButton={true}
        modelPathOne={"/models/buttons/home_button.glb"}
        modelPathTwo={"/models/buttons/home_button.glb"}
        position={[-1.85, -0.65, 4.5]}
        rotation={[Math.PI * 0.12, Math.PI * 0.16, -Math.PI * 0.08]}
        additionalUnclickHandler={() => {
          window.open("https://github.com/seungguini/vintage_turntable");
        }}
        additionalUnclickHandlerConfigs={{ setPlaying, playing }}
      />
    </>
  );
}