import { config } from "@react-spring/three";
import Button from "./Button";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const PrevButton = (props) => {
  const { nodes, materials } = useGLTF("/prev_button.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.uploads_files_2920617_Next.geometry}
        material={materials.Next_Mat}
        position={[0.01, 10.01, -5.18]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
    </group>
  );
};

useGLTF.preload("/prev_button.glb");

export default function Buttons({ playing, setPlaying, soundOn, setLol }) {
  const scaleNormal = 0.03;
  const scalePressed = 0.025;
  const hoveringScale = 0.032;
  const springConfig = config.bouncy;

  // Additional unclick handler for play button
  const playUnclickHandler = ({ setPlaying, playing }) => {
    setPlaying(!playing);
    console.log("setting play option");
  };

  // Additional unclick handler for sound button
  const soundUnclickHandler = ({ setLol, soundOn }) => {
    // setLol(!soundOn);
    console.log("setting sound option");
  };

  return (
    <>
      <Button
        id="soundOnOffButton"
        scaleNormal={scaleNormal}
        scalePressed={scalePressed}
        hoveringScale={hoveringScale}
        springConfig={springConfig}
        switchButton={true}
        modelPath1={"/models/buttons/soundon_button.glb"}
        modelPath2={"/models/buttons/soundoff_button.glb"}
        position={[2, -1, 4]}
        rotation={[0.5, 0.5, -0.25]}
        additionalUnclickHandler={soundUnclickHandler}
        additionalUnclickHandlerConfigs={(setLol, soundOn)}
      />
      <Button
        id="playPauseButton"
        scaleNormal={scaleNormal}
        scalePressed={scalePressed}
        hoveringScale={hoveringScale}
        springConfig={springConfig}
        switchButton={true}
        modelPath1={"/models/buttons/play_button.glb"}
        modelPath2={"/models/buttons/pause_button.glb"}
        position={[0, -1, 4]}
        rotation={[0.5, 0.5, -0.25]}
        additionalUnclickHandler={playUnclickHandler}
        additionalUnclickHandlerConfigs={{ setPlaying, playing }}
      />

      <Button
        id="nextButton"
        scaleNormal={scaleNormal}
        scalePressed={scalePressed}
        hoveringScale={hoveringScale}
        springConfig={springConfig}
        switchButton={true}
        modelPath1={"/models/buttons/next_button.glb"}
        modelPath2={"/models/buttons/next_button.glb"}
        position={[1, -1, 4]}
        rotation={[0.5, 0.5, -0.25]}
      />
      <Button
        gltfJsx={<PrevButton />}
        id="prevButton"
        scaleNormal={scaleNormal}
        scalePressed={scalePressed}
        hoveringScale={hoveringScale}
        springConfig={springConfig}
        modelPath1={"/models/buttons/prev_button.glb"}
        modelPath2={"/models/buttons/prev_button.glb"}
        position={[-1, -1, 4]}
        rotation={[0.5, 0.5, -0.25]}
      />
    </>
  );
}
