/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Room(props) {
  const { nodes, materials } = useGLTF("/models/room.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane088.geometry}
        material={nodes.Plane088.material}
        position={[-0.86, 1.25, -1.81]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane089.geometry}
        material={nodes.Plane089.material}
        position={[-0.86, 1.32, -1.94]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane090.geometry}
        material={nodes.Plane090.material}
        position={[-0.37, 1.95, -1.95]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1, 1, 0.87]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Material.002"]}
        position={[-0.71, 0.56, 1.19]}
        scale={[0.59, 0.08, 0.73]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[-1.78, 0.86, 1.63]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.19, 0.05, 0.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane092.geometry}
        material={materials.Sprei}
        position={[-0.33, 0.78, 1.19]}
        scale={[0.4, 0.59, 1.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane141.geometry}
        material={materials.Pillow}
        position={[-1.53, 0.77, 1.54]}
        rotation={[0, 0, -0.71]}
        scale={[0.25, 0.17, 0.36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane142.geometry}
        material={materials["Piloow.001"]}
        position={[-1.53, 0.77, 0.83]}
        rotation={[0, 0, -0.71]}
        scale={[0.25, 0.17, 0.36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane143.geometry}
        material={materials.Piloow}
        position={[-1.27, 0.72, 1.22]}
        rotation={[0, 0, -0.42]}
        scale={[0.22, 0.17, 0.36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Metalic.002"]}
        position={[1.83, 1.55, -1.87]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.07}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane145.geometry}
        material={materials["Metalic.002"]}
        position={[1.82, 1.55, -1.77]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.06, 0.07, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["Metalic.002"]}
        position={[1.83, 1.72, -1.87]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials["Metalic.002"]}
        position={[1.83, 1.72, -1.86]}
        rotation={[Math.PI / 2, -0.65, -Math.PI / 2]}
        scale={0.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane146.geometry}
        material={materials["Wood.002"]}
        position={[-1.39, 1.14, -0.69]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane149.geometry}
        material={materials["White Wood"]}
        position={[-1.3, 0.67, 0.05]}
        scale={[0.51, 1, 1.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[-0.96, 0.23, -0.2]}
        scale={[0.05, 0.03, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane150.geometry}
        material={materials["White Wood"]}
        position={[-0.91, 0.91, 0.05]}
        scale={[1, 1.04, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane151.geometry}
        material={materials["White Wood"]}
        position={[-1.3, 0.67, -1.5]}
        scale={[0.51, 1, 1.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[-0.96, 0.23, -1.75]}
        scale={[0.05, 0.03, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane152.geometry}
        material={materials["White Wood"]}
        position={[-0.91, 0.91, -1.5]}
        scale={[1, 1.04, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials["Wood.002"]}
        position={[-1.74, 1.39, -1.54]}
        scale={0.63}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={nodes.Cylinder005_1.material}
          position={[-0.24, 0.03, 0.42]}
          scale={[1.04, 0.82, 1.04]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_2.geometry}
          material={nodes.Cylinder006_2.material}
          position={[-0.24, -0.3, 0.42]}
          scale={[1.04, 0.82, 1.04]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={nodes.Cylinder007.material}
          position={[-0.23, 0, 0.42]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={nodes.Cylinder008.material}
          position={[-0.23, 0, 0.42]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane153.geometry}
          material={nodes.Plane153.material}
          position={[-0.25, -0.14, 0]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane154.geometry}
          material={nodes.Plane154.material}
          position={[0.02, -0.14, 0.42]}
        />
      </mesh>
      <group
        position={[-1.13, 1.15, -1.08]}
        rotation={[-Math.PI, 1.54, -Math.PI]}
        scale={[0.03, 0.03, 0.06]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane164.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane164_1.geometry}
          material={materials.Bootom}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane164_2.geometry}
          material={materials.Center}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials["mac mini.001"]}
        position={[-1.14, 1.15, -0.67]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.08}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane180.geometry}
          material={nodes.Plane180.material}
          position={[3.01, 0.06, -0.7]}
          rotation={[0.03, 0, 0]}
          scale={1.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane156.geometry}
          material={materials.Button}
          position={[3.02, 0.03, 0.56]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane157_2.geometry}
          material={materials.Button}
          position={[2.73, 0.02, 0.71]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane158.geometry}
          material={materials.Button}
          position={[2.29, 0.02, 0.71]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane159.geometry}
          material={materials.Button}
          position={[3.02, 0.05, -0.14]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane160.geometry}
          material={materials.Button}
          position={[2.43, 0.05, -0.13]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane161_2.geometry}
          material={materials.Button}
          position={[1.51, 0.03, 0.42]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane162_1.geometry}
          material={materials.Button}
          position={[1.51, 0.02, 0.71]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane163_1.geometry}
          material={materials.Button}
          position={[0.77, 0.04, 0.15]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane164_3.geometry}
          material={materials.Button}
          position={[-2.97, 0.02, 0.7]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane165_1.geometry}
          material={materials.Button}
          position={[0.81, 0.02, 0.71]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane166_1.geometry}
          material={materials.Button}
          position={[0.41, 0.02, 0.71]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane167.geometry}
          material={materials.Button}
          position={[0.01, 0.02, 0.71]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane168.geometry}
          material={materials.Button}
          position={[-1.07, 0.03, 0.72]}
          rotation={[0.07, 0, 0]}
          scale={0.91}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane169.geometry}
          material={materials.Button}
          position={[-2.18, 0.02, 0.71]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane170.geometry}
          material={materials.Button}
          position={[-2.58, 0.02, 0.71]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane171.geometry}
          material={materials.Button}
          position={[0.7, 0.03, 0.43]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane172.geometry}
          material={materials.Button}
          position={[-2.87, 0.03, 0.43]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane173.geometry}
          material={materials.Button}
          position={[-2.94, 0.04, 0.14]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane174.geometry}
          material={materials.Button}
          position={[-2.97, 0.05, -0.14]}
          rotation={[0.03, 0, 0]}
          scale={[1.53, 0.96, 0.96]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane175.geometry}
          material={materials.Button}
          position={[0.81, 0.05, -0.42]}
          rotation={[0.03, 0, 0]}
          scale={[1.53, 0.96, 0.96]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane176.geometry}
          material={materials.Button}
          position={[-1.08, 0.03, 0.43]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane177.geometry}
          material={materials.Button}
          position={[-1.09, 0.04, 0.14]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane178.geometry}
          material={materials.Button}
          position={[-0.87, 0.05, -0.14]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane179.geometry}
          material={materials.Button}
          position={[-1.31, 0.05, -0.42]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane181.geometry}
          material={materials.Button}
          position={[1.51, 0.05, -0.42]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane182.geometry}
          material={materials.Button}
          position={[-0.87, 0.06, -0.7]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane183.geometry}
          material={materials.Button}
          position={[-2.97, 0.06, -0.7]}
          rotation={[0.03, 0, 0]}
          scale={0.96}
        />
      </mesh>
      <group position={[-1.15, 1.15, -0.72]} scale={[1, 1, 0.88]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane195_1.geometry}
          material={materials.Mousepad}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane195_2.geometry}
          material={materials.mousepad}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane185.geometry}
        material={nodes.Plane185.material}
        position={[-1.73, 1.22, -0.68]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Base.001"]}
        position={[1.3, 1.41, -1.85]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Base.001"]}
        position={[1.3, 1.4, -1.77]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[1.3, 2.16, -1.88]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.86, 1, 0.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane075.geometry}
        material={materials.Base}
        position={[0, 3.32, -2.01]}
        scale={[1.01, 0.02, 1.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane085.geometry}
        material={materials.Base}
        position={[-2.02, 3.32, 0.05]}
        scale={[1.27, 0.02, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane087.geometry}
        material={nodes.Plane087.material}
        position={[0, 0.2, 0]}
      />
      <group position={[0, 0.2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane104.geometry}
          material={materials.Floor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane104_1.geometry}
          material={materials["Floor.002"]}
        />
      </group>
      <group position={[0, 0.2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane157.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane157_1.geometry}
          material={materials["Wall.001"]}
        />
      </group>
      <group position={[0, 0.2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane161.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane161_1.geometry}
          material={materials.Wall}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane191.geometry}
        material={nodes.Plane191.material}
        position={[-0.56, 0.77, -0.74]}
        scale={0.31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane192.geometry}
        material={materials["Chair Pullow"]}
        position={[-0.56, 0.76, -0.74]}
        scale={0.31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane193.geometry}
        material={materials.Plastic}
        position={[-0.38, 0.78, -0.74]}
        scale={0.72}
      />
      <group
        position={[-0.19, 1.16, -0.74]}
        rotation={[0, 0, 1.41]}
        scale={[0.4, 0.41, 0.43]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane207_1.geometry}
          material={materials["Plastic.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane207_2.geometry}
          material={materials.Trans}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath.geometry}
        material={nodes.NurbsPath.material}
        position={[-0.56, 0.78, -0.74]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.14}
      />
      <group position={[-0.56, 1.14, -0.37]} scale={0.72}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane210.geometry}
          material={materials.Plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane210_1.geometry}
          material={materials["Chair Pullow"]}
        />
      </group>
      <group position={[-0.54, 0.41, -0.74]} scale={-0.03}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials.Plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_1.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials.Plastic}
        position={[-0.54, 0.41, -0.74]}
        scale={0.71}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials.Ban}
        position={[-0.54, 0.45, -0.73]}
        scale={0.96}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials.Ban}
        position={[-0.54, 0.45, -0.73]}
        rotation={[0, 1.06, 0]}
        scale={0.96}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials.Ban}
        position={[-0.54, 0.45, -0.73]}
        rotation={[-Math.PI, 1.03, -Math.PI]}
        scale={0.96}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials.Ban}
        position={[-0.54, 0.45, -0.73]}
        rotation={[Math.PI, -0.02, Math.PI]}
        scale={0.96}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials.Ban}
        position={[-0.54, 0.45, -0.73]}
        rotation={[Math.PI, -1.04, Math.PI]}
        scale={0.96}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials.Ban}
        position={[-0.54, 0.45, -0.73]}
        rotation={[0, -1.05, 0]}
        scale={0.96}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane186.geometry}
        material={materials.Metalic}
        position={[-1.81, 1.24, -0.68]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane187.geometry}
        material={materials["Metalic.001"]}
        position={[-1.89, 1.27, -0.02]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.03, 1, 0.95]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane188.geometry}
        material={materials.Gagang}
        position={[-1.78, 1.15, -0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane189.geometry}
        material={materials["Metalic.001"]}
        position={[-1.87, 1.25, -0.02]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.72, 3.31, 0.76]}
      />
      <group
        position={[-1.78, 1.59, -0.68]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.29, 1.29, 1.25]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane202_1.geometry}
          material={materials.Metalic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane202_2.geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane202_3.geometry}
          material={materials["Screen.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane043.geometry}
        material={materials["Jar 2"]}
        position={[-1.83, 1.4, -1.34]}
        rotation={[0, 0.17, 0]}
        scale={0.78}
      />
      <group
        position={[-1.86, 1.55, -1.35]}
        rotation={[0.17, 0.04, 1.83]}
        scale={0.78}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane047.geometry}
          material={materials.Scis}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane047_1.geometry}
          material={materials["Brush.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Jar.geometry}
        material={materials["Jar.001"]}
        position={[-1.83, 1.4, -1.47]}
        rotation={[0, -0.09, 0]}
      >
        <group
          position={[0.01, 0, 0.02]}
          rotation={[0.09, 0.09, -0.01]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane052_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane052_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[-0.01, 0, 0.02]}
          rotation={[0.11, -0.68, 0.07]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane053_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane053_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[0, 0, 0.02]}
          rotation={[0.09, -0.21, 0.02]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane054_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane054_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[-0.02, 0, 0.01]}
          rotation={[0.15, -0.93, 0.12]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane055_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane055_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[-0.03, 0.01, 0]}
          rotation={[0.25, -1.22, 0.24]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane056_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane056_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[-0.03, 0, -0.01]}
          rotation={[1.88, -1.48, 1.88]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane057_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane057_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[-0.02, 0, -0.02]}
          rotation={[2.82, -1.29, 2.83]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane058_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane058_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[-0.01, 0, -0.03]}
          rotation={[3.01, -0.84, 3.04]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane059_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane059_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[0, 0.02, -0.03]}
          rotation={[3.05, -0.38, 3.11]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane060_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane060_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[0.02, 0, -0.02]}
          rotation={[3.05, 0.14, -3.13]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane061_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane061_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[0.03, 0, -0.02]}
          rotation={[3.05, 0.44, -3.1]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane062_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane062_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[0.03, 0.01, -0.01]}
          rotation={[2.99, 0.95, -3.02]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane063_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane063_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[0.02, 0, 0]}
          rotation={[2.77, 1.33, -2.78]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane064_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane064_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[0.02, 0, 0.01]}
          rotation={[0.51, 1.39, -0.5]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane065_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane065_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[0.01, 0, 0.02]}
          rotation={[0.13, 0.86, -0.1]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane066_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane066_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[-0.01, 0.02, 0.01]}
          rotation={[0.09, -0.13, 0.01]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane067_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane067_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[-0.01, 0, 0]}
          rotation={[0.1, -0.58, 0.06]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane068_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane068_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[0.01, 0, 0.01]}
          rotation={[0.09, -0.16, 0.01]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane069_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane069_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[0, 0, -0.01]}
          rotation={[0.13, -0.86, 0.1]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane070_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane070_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[0.01, 0, 0]}
          rotation={[0.17, -1.01, 0.14]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane071_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane071_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[-0.02, 0, -0.01]}
          rotation={[2.75, -1.34, 2.76]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane072_1.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane072_2.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
        <group
          position={[0.01, 0, -0.01]}
          rotation={[3.05, -0.28, 3.12]}
          scale={[1.2, 1, 1.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane073.geometry}
            material={materials.Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane073_1.geometry}
            material={materials["Pencil.001"]}
          />
        </group>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane050.geometry}
        material={materials["Brush.001"]}
        position={[-1.83, 1.54, -1.36]}
        rotation={[1.14, 0.07, -0.16]}
        scale={0.78}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[-1.68, 1.48, -1.41]}
        rotation={[0, 0.07, 0]}
        scale={[0.05, 0.08, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube097.geometry}
        material={materials["Material.024"]}
        position={[-1.74, 1.31, -1.66]}
        rotation={[0, 0.17, 0]}
        scale={[0.86, 0.52, 0.86]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube098.geometry}
          material={nodes.Cube098.material}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube099.geometry}
        material={materials["Material.025"]}
        position={[-1.74, 1.26, -1.66]}
        rotation={[0, 1.45, 0]}
        scale={[0.86, 0.52, 0.86]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube100.geometry}
          material={nodes.Cube100.material}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017.geometry}
        material={materials["Material.022"]}
        position={[-1.69, 1.4, -1.68]}
        scale={0.74}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert002.geometry}
          material={materials["Material.023"]}
          position={[-0.06, 0.14, 0.04]}
          rotation={[Math.PI, -0.49, Math.PI]}
          scale={[1.08, 1.03, 3.67]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert003.geometry}
          material={materials["Material.023"]}
          position={[-0.01, 0.14, -0.04]}
          rotation={[0, 1.45, 0]}
          scale={[0.84, 0.81, 2.88]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert004.geometry}
          material={materials["Material.023"]}
          position={[-0.07, 0.14, -0.02]}
          rotation={[-Math.PI, 0.25, -Math.PI]}
          scale={[1.11, 1.07, 3.79]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert005.geometry}
          material={materials["Material.023"]}
          position={[-0.03, 0.14, 0.07]}
          rotation={[0, -1.36, 0]}
          scale={[0.93, 0.89, 3.17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert006.geometry}
          material={materials["Material.023"]}
          position={[-0.04, 0.11, 0.02]}
          rotation={[Math.PI, -1.32, Math.PI]}
          scale={[1.36, 1.32, 3.58]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert007.geometry}
          material={materials["Material.023"]}
          position={[-0.04, 0.11, 0.02]}
          rotation={[0, 0.75, 0]}
          scale={[1.36, 1.32, 3.58]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert008.geometry}
          material={materials["Material.023"]}
          position={[0.01, 0.14, 0.02]}
          rotation={[0, -0.05, 0]}
          scale={[1, 0.96, 3.4]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane196.geometry}
        material={materials.Clock}
        position={[-1.64, 1.48, -1.41]}
        rotation={[1.21, 0.03, -1.64]}
        scale={[0, 0, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane197.geometry}
        material={materials.Clock}
        position={[-1.64, 1.48, -1.41]}
        rotation={[2.14, -0.04, -1.63]}
        scale={[0, 0, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane198.geometry}
        material={materials.Clock}
        position={[-1.64, 1.48, -1.41]}
        rotation={[-0.82, 0.05, -1.52]}
        scale={[0, 0, 0.01]}
      />
      <group position={[-1.72, 1.23, -1.39]} scale={[0.12, 0.12, 0.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane209.geometry}
          material={materials.Kalkulator}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane209_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane209_2.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane209_3.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[-1.71, 1.23, -1.31]} scale={[0.03, 0.11, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane211.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane211_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane201.geometry}
        material={nodes.Plane201.material}
        position={[-1.71, 1.23, -1.45]}
        scale={[0.03, 0.11, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane202.geometry}
        material={nodes.Plane202.material}
        position={[-1.64, 1.23, -1.45]}
        scale={[0.03, 0.11, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane203.geometry}
        material={nodes.Plane203.material}
        position={[-1.71, 1.23, -1.49]}
        scale={[0.03, 0.11, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane204.geometry}
        material={nodes.Plane204.material}
        position={[-1.74, 1.23, -1.38]}
        scale={[0.01, 0.11, 0.02]}
      />
      <group
        position={[0.2, 1.88, -1.86]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.86, 0.86, 0.88]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane219.geometry}
          material={materials.Frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane219_1.geometry}
          material={materials.glass}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["png-apple-logo-9711"].geometry}
        material={materials["png-apple-logo-9711"]}
        position={[-1.82, 1.26, -0.02]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["png-apple-logo-9711001"].geometry}
        material={materials["png-apple-logo-9711"]}
        position={[-1.75, 1.36, -0.68]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.07}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Bed wood"]}
        position={[-1.81, 0.82, 1.19]}
        scale={[0.47, 0.59, 0.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials["Bed wood"]}
        position={[-1.16, 0.43, 1.19]}
        scale={[0.59, 0.09, 0.73]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials["Bed wood"]}
        position={[0.45, 0.56, 1.19]}
        scale={0.59}
      />
      <group
        position={[-1.9, 2.45, -0.92]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1, 0.95, 0.43]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane220.geometry}
          material={materials.Framee}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane220_1.geometry}
          material={materials["image.001"]}
        />
      </group>
      <group
        position={[-1.9, 2.45, -0.23]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.95}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane218.geometry}
          material={materials.Framee}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane218_1.geometry}
          material={materials.image}
        />
      </group>
      <group
        position={[-1.87, 2.31, 1.14]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.5, 1, 0.61]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane221.geometry}
          material={materials.Fraa}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane221_1.geometry}
          material={materials.imgg}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
